name: bigun
description: A social media app for sharing audio stories.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  record: ^4.4.4
  permission_handler: ^10.2.0
  intl: ^0.18.0
  path_provider: ^2.0.15
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
